### ISSUE TITLE
Force renjin to compile with other gcc version

### ISSUE THREAD

**Issue by nicolas-f** [bedatadriven/gcc-bridge-example#2]
Is there a way to force renjin to use an available version of gcc ?

I'm under OpenSuse and there is no way to install gcc 4.6 (without having to compile it from source under an alternative folder)

**Comment by akbertram** [comment]
Unfortunately GCC Bridge is quite sensitive to the GCC version because it includes a GCC plugin which must be linked against GCC itself and necessarily depends on many details of the internal GCC implementation.

We recently upgraded GCC-Bridge to compile against GCC 4.7. Does this solve the problem?

I think by the end of this year we should be able to compile enough of GCC itself to support a pure-Java tool chain which hopefully will put an end to these installation headaches!

**Comment by nicolas-f** [comment]
Hi,

Thanks for the answer. I'm sorry my gcc version is:
```gcc version 4.8.5 (SUSE Linux) ```

Is there a guide in order to compile ourself the plugin your are talking about for a more recent version of gcc ?

Thanks

**Comment by nicolas-f** [comment]
I will looking for building my project under a virtual machine or on a Travis worker. It will be more easier than trying to compile&install another version of gcc. Thanks for support.

**Comment by akbertram** [comment]
Ok, great. We will need to migrate to 4.8 (or perhaps directly to 5.x or 6.x) in the future, but [migrating to new GCC versions](https://github.com/bedatadriven/renjin/pull/252) will require significant changes to the plugin source.

You can take a look at Renjin's [Vagrantfile](https://github.com/bedatadriven/renjin/blob/master/Vagrantfile) as a start.

**Comment by akbertram** [comment]
Also, are you sure there aren't gcc-4.7.x binaries available for OpenSUSE? See this link for example:
http://software.opensuse.org/download.html?project=devel%3Agcc&package=gcc47

**Comment by nicolas-f** [comment]
The devel repository is deprecated. I'm using openSUSE Leap 42.1

I've installed vagrant, so gcc version is not an issue anymore. Thanks
